import type {
  Campaign,
  ContentItem,
  CalendarEvent,
  TeamMember,
  Task,
  Activity,
  Notification,
  AIConversation,
} from "@/types";

export const campaigns: Campaign[] = [
  {
    id: "c1",
    name: "Summer Launch 2025",
    status: "active",
    channel: ["instagram", "facebook", "email"],
    budget: 12000,
    spent: 7400,
    startDate: "2025-06-01",
    endDate: "2025-08-31",
    progress: 62,
    goal: "Drive 5,000 signups for new product line",
    reach: 248000,
    engagement: 6.8,
    conversions: 1820,
    color: "hsl(243 75% 59%)",
    owner: { name: "Sarah Chen", initials: "SC" },
  },
  {
    id: "c2",
    name: "Brand Awareness Q3",
    status: "active",
    channel: ["linkedin", "twitter", "blog"],
    budget: 8000,
    spent: 3200,
    startDate: "2025-07-01",
    endDate: "2025-09-30",
    progress: 28,
    goal: "Increase brand mentions by 40%",
    reach: 156000,
    engagement: 4.2,
    conversions: 640,
    color: "hsl(158 64% 52%)",
    owner: { name: "Marcus Reid", initials: "MR" },
  },
  {
    id: "c3",
    name: "Holiday Email Series",
    status: "scheduled",
    channel: ["email"],
    budget: 4000,
    spent: 0,
    startDate: "2025-12-01",
    endDate: "2025-12-25",
    progress: 15,
    goal: "Reactivate 2,000 dormant subscribers",
    reach: 0,
    engagement: 0,
    conversions: 0,
    color: "hsl(38 92% 50%)",
    owner: { name: "Priya Patel", initials: "PP" },
  },
  {
    id: "c4",
    name: "Webinar Promotion",
    status: "active",
    channel: ["linkedin", "email", "twitter"],
    budget: 5000,
    spent: 4100,
    startDate: "2025-07-10",
    endDate: "2025-07-30",
    progress: 82,
    goal: "Register 800 attendees for AI marketing webinar",
    reach: 92000,
    engagement: 8.1,
    conversions: 612,
    color: "hsl(262 83% 58%)",
    owner: { name: "Sarah Chen", initials: "SC" },
  },
  {
    id: "c5",
    name: "Influencer Collab Drop",
    status: "draft",
    channel: ["instagram", "facebook"],
    budget: 15000,
    spent: 0,
    startDate: "2025-09-15",
    endDate: "2025-10-15",
    progress: 8,
    goal: "Generate 10M impressions via creator network",
    reach: 0,
    engagement: 0,
    conversions: 0,
    color: "hsl(199 89% 48%)",
    owner: { name: "James Wong", initials: "JW" },
  },
  {
    id: "c6",
    name: "Customer Spotlight Series",
    status: "completed",
    channel: ["linkedin", "blog"],
    budget: 3000,
    spent: 2900,
    startDate: "2025-04-01",
    endDate: "2025-05-31",
    progress: 100,
    goal: "Publish 6 case studies",
    reach: 78000,
    engagement: 5.4,
    conversions: 230,
    color: "hsl(142 71% 45%)",
    owner: { name: "Marcus Reid", initials: "MR" },
  },
];

export const contentItems: ContentItem[] = [
  {
    id: "ct1",
    type: "instagram",
    platform: "Instagram",
    title: "Summer Launch Teaser",
    body: "Something big is coming. ☀️ Our most anticipated launch yet arrives in 48 hours. Set your reminders — you won't want to miss this.",
    caption: "The wait is almost over. Tap the link in bio to be the first to know. 🚀",
    hashtags: ["#SummerLaunch", "#NewDrop", "#StayTuned", "#BrandName"],
    cta: "Link in bio",
    status: "scheduled",
    scheduledFor: "2025-07-26T10:00",
    campaign: "Summer Launch 2025",
    favorite: true,
  },
  {
    id: "ct2",
    type: "linkedin",
    platform: "LinkedIn",
    title: "Thought Leadership Post",
    body: "Marketing in 2025 isn't about more channels. It's about smarter orchestration.\n\nAfter working with 200+ brands, we noticed one pattern: teams that align their content pillars with funnel stages see 3x higher conversion.\n\nHere's the framework we use ↓",
    cta: "Read the full breakdown in comments",
    status: "draft",
    campaign: "Brand Awareness Q3",
  },
  {
    id: "ct3",
    type: "email",
    platform: "Email",
    title: "Webinar Reminder — Tomorrow",
    body: "Hi {first_name},\n\nJust a quick reminder that our live session 'AI-Powered Marketing Operations' starts tomorrow at 2 PM EST.\n\nWe'll cover:\n• How to automate content workflows\n• Building a single source of truth for campaigns\n• Measuring what actually matters\n\nSee you there!",
    cta: "Join the webinar",
    status: "approval",
    scheduledFor: "2025-07-25T14:00",
    campaign: "Webinar Promotion",
  },
  {
    id: "ct4",
    type: "twitter",
    platform: "Twitter / X",
    title: "Product Thread",
    body: "We analyzed 10,000 marketing campaigns. Here's what the top 1% do differently 🧵",
    hashtags: ["#MarketingOps", "#GrowthHacking"],
    status: "published",
    campaign: "Brand Awareness Q3",
    favorite: true,
  },
  {
    id: "ct5",
    type: "blog",
    platform: "Blog",
    title: "The Complete Guide to AI Marketing Operations",
    body: "Marketing teams today manage more complexity than ever before. Between fragmented channels, rising content demands, and pressure to prove ROI, traditional workflows are breaking down. In this guide, we explore how AI-native operations reshape the way teams plan, produce, and measure...",
    status: "draft",
    campaign: "Brand Awareness Q3",
  },
  {
    id: "ct6",
    type: "facebook",
    platform: "Facebook",
    title: "Community Story",
    body: "Behind every great product is a community that believed in it early. Today we're celebrating 10,000 of you who've been with us since day one. 🎉",
    status: "scheduled",
    scheduledFor: "2025-07-28T15:00",
    campaign: "Summer Launch 2025",
  },
];

export const calendarEvents: CalendarEvent[] = [
  { id: "e1", title: "Summer teaser post", date: "2025-07-26", platform: "instagram", status: "scheduled", time: "10:00" },
  { id: "e2", title: "Webinar reminder email", date: "2025-07-25", platform: "email", status: "approval", time: "14:00" },
  { id: "e3", title: "LinkedIn thought post", date: "2025-07-27", platform: "linkedin", status: "draft" },
  { id: "e4", title: "Product thread", date: "2025-07-24", platform: "twitter", status: "published", time: "09:00" },
  { id: "e5", title: "Community story", date: "2025-07-28", platform: "facebook", status: "scheduled", time: "15:00" },
  { id: "e6", title: "Blog guide publish", date: "2025-07-30", platform: "blog", status: "draft" },
  { id: "e7", title: "Influencer brief", date: "2025-07-29", platform: "instagram", status: "approval", time: "11:00" },
  { id: "e8", title: "Q3 newsletter", date: "2025-07-31", platform: "email", status: "draft" },
  { id: "e9", title: "Customer spotlight", date: "2025-07-22", platform: "linkedin", status: "published" },
];

export const teamMembers: TeamMember[] = [
  { id: "t1", name: "Sarah Chen", email: "sarah@strategix.io", role: "owner", initials: "SC", color: "hsl(243 75% 59%)", tasksAssigned: 12, tasksCompleted: 8, lastActive: "2m ago" },
  { id: "t2", name: "Marcus Reid", email: "marcus@strategix.io", role: "admin", initials: "MR", color: "hsl(158 64% 52%)", tasksAssigned: 9, tasksCompleted: 6, lastActive: "1h ago" },
  { id: "t3", name: "Priya Patel", email: "priya@strategix.io", role: "editor", initials: "PP", color: "hsl(38 92% 50%)", tasksAssigned: 15, tasksCompleted: 11, lastActive: "5m ago" },
  { id: "t4", name: "James Wong", email: "james@strategix.io", role: "editor", initials: "JW", color: "hsl(262 83% 58%)", tasksAssigned: 7, tasksCompleted: 3, lastActive: "3h ago" },
  { id: "t5", name: "Elena Rodriguez", email: "elena@strategix.io", role: "viewer", initials: "ER", color: "hsl(199 89% 48%)", tasksAssigned: 4, tasksCompleted: 4, lastActive: "1d ago" },
];

export const tasks: Task[] = [
  { id: "tk1", title: "Approve Instagram teaser copy", status: "review", assignee: "Sarah Chen", dueDate: "2025-07-25", campaign: "Summer Launch 2025" },
  { id: "tk2", title: "Draft Q3 blog guide outline", status: "in-progress", assignee: "Marcus Reid", dueDate: "2025-07-28", campaign: "Brand Awareness Q3" },
  { id: "tk3", title: "Design webinar landing page", status: "todo", assignee: "Priya Patel", dueDate: "2025-07-26", campaign: "Webinar Promotion" },
  { id: "tk4", title: "Schedule influencer outreach", status: "todo", assignee: "James Wong", dueDate: "2025-08-01", campaign: "Influencer Collab Drop" },
  { id: "tk5", title: "Review email sequence performance", status: "done", assignee: "Sarah Chen", dueDate: "2025-07-20", campaign: "Webinar Promotion" },
  { id: "tk6", title: "Finalize holiday email calendar", status: "in-progress", assignee: "Priya Patel", dueDate: "2025-08-05", campaign: "Holiday Email Series" },
];

export const activities: Activity[] = [
  { id: "a1", user: "Priya Patel", initials: "PP", action: "submitted content for approval", target: "Webinar Reminder Email", time: "5m ago", type: "created" },
  { id: "a2", user: "Sarah Chen", initials: "SC", action: "approved", target: "Instagram Teaser Copy", time: "22m ago", type: "approved" },
  { id: "a3", user: "Marcus Reid", initials: "MR", action: "published", target: "Product Thread on Twitter", time: "1h ago", type: "published" },
  { id: "a4", user: "AI Assistant", initials: "AI", action: "generated strategy for", target: "Summer Launch 2025", time: "2h ago", type: "created" },
  { id: "a5", user: "James Wong", initials: "JW", action: "commented on", target: "Influencer Collab brief", time: "3h ago", type: "commented" },
  { id: "a6", user: "Marcus Reid", initials: "MR", action: "updated budget for", target: "Brand Awareness Q3", time: "5h ago", type: "updated" },
];

export const notifications: Notification[] = [
  { id: "n1", icon: "approval", title: "Content awaiting approval", description: "Priya Patel submitted 'Webinar Reminder Email' for your review.", time: "5m ago", read: false, group: "today" },
  { id: "n2", icon: "ai", title: "AI strategy ready", description: "Your campaign strategy for 'Summer Launch 2025' has been generated.", time: "2h ago", read: false, group: "today" },
  { id: "n3", icon: "published", title: "Post published successfully", description: "'Product Thread' is now live on Twitter.", time: "1h ago", read: true, group: "today" },
  { id: "n4", icon: "comment", title: "New comment", description: "James Wong commented on the Influencer Collab brief.", time: "3h ago", read: true, group: "today" },
  { id: "n5", icon: "mention", title: "You were mentioned", description: "Marcus Reid mentioned you in Brand Awareness Q3.", time: "Yesterday at 4:32 PM", read: true, group: "yesterday" },
  { id: "n6", icon: "system", title: "Weekly report ready", description: "Your marketing performance summary for this week is available.", time: "Yesterday at 9:00 AM", read: true, group: "yesterday" },
  { id: "n7", icon: "approval", title: "2 items need review", description: "You have 2 content pieces pending approval.", time: "2 days ago", read: true, group: "this-week" },
  { id: "n8", icon: "ai", title: "AI insights updated", description: "New performance insights are available in Analytics.", time: "3 days ago", read: true, group: "this-week" },
];

export const aiConversations: AIConversation[] = [
  { id: "ai1", title: "Summer launch strategy", preview: "Generate a full funnel for our summer product...", time: "2h ago" },
  { id: "ai2", title: "Instagram caption ideas", preview: "Write 5 caption variations for the teaser post", time: "Yesterday" },
  { id: "ai3", title: "Audience persona research", preview: "Who is the ideal customer for our webinar?", time: "2 days ago" },
  { id: "ai4", title: "Email subject line A/B test", preview: "Suggest 10 subject lines optimized for open rate", time: "3 days ago" },
];

export const aiPromptSuggestions = [
  "Generate a 30-day content calendar for Instagram",
  "Write 5 LinkedIn posts about AI in marketing",
  "Create a campaign strategy for a new product launch",
  "Suggest audience personas for a B2B SaaS product",
  "Draft an email sequence to re-engage inactive users",
  "Generate hashtags for a summer fashion campaign",
];

export const channels = [
  { id: "instagram", name: "Instagram", color: "hsl(326 75% 56%)", icon: "instagram" },
  { id: "linkedin", name: "LinkedIn", color: "hsl(210 100% 50%)", icon: "linkedin" },
  { id: "facebook", name: "Facebook", color: "hsl(221 83% 53%)", icon: "facebook" },
  { id: "twitter", name: "Twitter / X", color: "hsl(203 89% 53%)", icon: "twitter" },
  { id: "email", name: "Email", color: "hsl(262 83% 58%)", icon: "mail" },
  { id: "blog", name: "Blog", color: "hsl(243 75% 59%)", icon: "file-text" },
] as const;

export const user = {
  name: "Sarah Chen",
  email: "sarah@strategix.io",
  initials: "SC",
  role: "Owner",
  workspace: "Strategix HQ",
};
